### ISSUE TITLE
6/5 ~ 7

### ISSUE THREAD

**Issue by anemoneflower** [anemoneflower/HCI_ReadIT#23]
Write ToDo here.

**Comment by anemoneflower** [comment]
서윤
- [ ] read_note 엄마디자인
- [ ] read_note routing

**Comment by coolofficials** [comment]
채은

isSelected
isSignIn

**Comment by coolofficials** [comment]
시원

board layout
mainpage layout
searched page layout

**Comment by anemoneflower** [comment]
채은 
- [ ] Global variable db 연결 (selectedBookKey, userkey)
- [ ] isSelected 연결
- [ ] isSignIn 새로고침할때 남아있는거 고치기
- [ ] Signin Layout

**Comment by anemoneflower** [comment]
서윤
- [ ] WriteNote design
- [ ] global db 생기면 동작 연결
