### ISSUE TITLE
Remain tasks

### ISSUE THREAD

**Issue by navy3690** [anemoneflower/HCI_ReadIT#44]
- [x] mynote 만들기 : 채은
- [x] mybook 만들기 : 채은
- [x] isSelected : 채은 시원
- [ ] 새로고침 방지 : 채은 서윤
autocomplete 
- [x] (select, 
- [x] visible, 
- [x] hover랑 select 블럭) : 채은 시원
- [x] 좋아요, view increase : 서윤
- [x] card layout : 시원
- [x] signin 안보이는 거 : 시원
- [x] submit button style in write note : 시원
- [x] book-note-board style : 시원 > entry reverse / box 크기 제한
- [x] signin enter 추가 : 채은
- [x] card range 나오는 부분, if wholebook    page_range = wholebook : 서윤

**Comment by anemoneflower** [comment]
TAB icon & title fixed

**Comment by anemoneflower** [comment]
- [ ] Dummy data
